/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TeamRouteImport } from './routes/team'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as PayIndexRouteImport } from './routes/pay.index'
import { Route as PayAffirmRouteImport } from './routes/pay.affirm'
import { Route as PaySuccessRouteImport } from './routes/pay.success'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAccessRouteImport } from './routes/studio/access'
import { Route as StudioCalendarRouteImport } from './routes/studio/calendar'
import { Route as StudioClientsRouteImport } from './routes/studio/clients'
import { Route as StudioHoursRouteImport } from './routes/studio/hours'
import { Route as StudioInventoryRouteImport } from './routes/studio/inventory'
import { Route as StudioMenuRouteImport } from './routes/studio/menu'
import { Route as StudioPaymentsRouteImport } from './routes/studio/payments'
import { Route as StudioPosRouteImport } from './routes/studio/pos'
import { Route as StudioReportsRouteImport } from './routes/studio/reports'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as StudioReportsIndexRouteImport } from './routes/studio/reports.index'
import { Route as StudioReportsHoursRouteImport } from './routes/studio/reports.hours'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIndexRoute = PayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayRoute,
} as any)
const PayAffirmRoute = PayAffirmRouteImport.update({
  id: '/affirm',
  path: '/affirm',
  getParentRoute: () => PayRoute,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PayRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAccessRoute = StudioAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCalendarRoute = StudioCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudioRoute,
} as any)
const StudioClientsRoute = StudioClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => StudioRoute,
} as any)
const StudioHoursRoute = StudioHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInventoryRoute = StudioInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMenuRoute = StudioMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPaymentsRoute = StudioPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPosRoute = StudioPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => StudioRoute,
} as any)
const StudioReportsRoute = StudioReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioReportsIndexRoute = StudioReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioReportsRoute,
} as any)
const StudioReportsHoursRoute = StudioReportsHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => StudioReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRouteWithChildren
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRouteWithChildren
  '/team': typeof TeamRoute
  '/visits': typeof VisitsRoute
  '/pay/affirm': typeof PayAffirmRoute
  '/pay/success': typeof PaySuccessRoute
  '/studio/access': typeof StudioAccessRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/clients': typeof StudioClientsRoute
  '/studio/hours': typeof StudioHoursRoute
  '/studio/inventory': typeof StudioInventoryRoute
  '/studio/menu': typeof StudioMenuRoute
  '/studio/payments': typeof StudioPaymentsRoute
  '/studio/pos': typeof StudioPosRoute
  '/studio/reports': typeof StudioReportsRouteWithChildren
  '/pay/': typeof PayIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/reports/hours': typeof StudioReportsHoursRoute
  '/studio/reports/': typeof StudioReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/team': typeof TeamRoute
  '/visits': typeof VisitsRoute
  '/pay/affirm': typeof PayAffirmRoute
  '/pay/success': typeof PaySuccessRoute
  '/studio/access': typeof StudioAccessRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/clients': typeof StudioClientsRoute
  '/studio/hours': typeof StudioHoursRoute
  '/studio/inventory': typeof StudioInventoryRoute
  '/studio/menu': typeof StudioMenuRoute
  '/studio/payments': typeof StudioPaymentsRoute
  '/studio/pos': typeof StudioPosRoute
  '/pay': typeof PayIndexRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/reports/hours': typeof StudioReportsHoursRoute
  '/studio/reports': typeof StudioReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/pay': typeof PayRouteWithChildren
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRouteWithChildren
  '/team': typeof TeamRoute
  '/visits': typeof VisitsRoute
  '/pay/affirm': typeof PayAffirmRoute
  '/pay/success': typeof PaySuccessRoute
  '/studio/access': typeof StudioAccessRoute
  '/studio/calendar': typeof StudioCalendarRoute
  '/studio/clients': typeof StudioClientsRoute
  '/studio/hours': typeof StudioHoursRoute
  '/studio/inventory': typeof StudioInventoryRoute
  '/studio/menu': typeof StudioMenuRoute
  '/studio/payments': typeof StudioPaymentsRoute
  '/studio/pos': typeof StudioPosRoute
  '/studio/reports': typeof StudioReportsRouteWithChildren
  '/pay/': typeof PayIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/studio/reports/hours': typeof StudioReportsHoursRoute
  '/studio/reports/': typeof StudioReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/login'
    | '/pay'
    | '/services'
    | '/shop'
    | '/studio'
    | '/team'
    | '/visits'
    | '/pay/affirm'
    | '/pay/success'
    | '/studio/access'
    | '/studio/calendar'
    | '/studio/clients'
    | '/studio/hours'
    | '/studio/inventory'
    | '/studio/menu'
    | '/studio/payments'
    | '/studio/pos'
    | '/studio/reports'
    | '/pay/'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/reports/hours'
    | '/studio/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/services'
    | '/shop'
    | '/team'
    | '/visits'
    | '/pay/affirm'
    | '/pay/success'
    | '/studio/access'
    | '/studio/calendar'
    | '/studio/clients'
    | '/studio/hours'
    | '/studio/inventory'
    | '/studio/menu'
    | '/studio/payments'
    | '/studio/pos'
    | '/pay'
    | '/studio'
    | '/api/auth/$'
    | '/studio/reports/hours'
    | '/studio/reports'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/login'
    | '/pay'
    | '/services'
    | '/shop'
    | '/studio'
    | '/team'
    | '/visits'
    | '/pay/affirm'
    | '/pay/success'
    | '/studio/access'
    | '/studio/calendar'
    | '/studio/clients'
    | '/studio/hours'
    | '/studio/inventory'
    | '/studio/menu'
    | '/studio/payments'
    | '/studio/pos'
    | '/studio/reports'
    | '/pay/'
    | '/studio/'
    | '/api/auth/$'
    | '/studio/reports/hours'
    | '/studio/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  PayRoute: typeof PayRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  StudioRoute: typeof StudioRouteWithChildren
  TeamRoute: typeof TeamRoute
  VisitsRoute: typeof VisitsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/': {
      id: '/pay/'
      path: '/'
      fullPath: '/pay/'
      preLoaderRoute: typeof PayIndexRouteImport
      parentRoute: typeof PayRoute
    }
    '/pay/affirm': {
      id: '/pay/affirm'
      path: '/affirm'
      fullPath: '/pay/affirm'
      preLoaderRoute: typeof PayAffirmRouteImport
      parentRoute: typeof PayRoute
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof PayRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/access': {
      id: '/studio/access'
      path: '/access'
      fullPath: '/studio/access'
      preLoaderRoute: typeof StudioAccessRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/calendar': {
      id: '/studio/calendar'
      path: '/calendar'
      fullPath: '/studio/calendar'
      preLoaderRoute: typeof StudioCalendarRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/clients': {
      id: '/studio/clients'
      path: '/clients'
      fullPath: '/studio/clients'
      preLoaderRoute: typeof StudioClientsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/hours': {
      id: '/studio/hours'
      path: '/hours'
      fullPath: '/studio/hours'
      preLoaderRoute: typeof StudioHoursRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/inventory': {
      id: '/studio/inventory'
      path: '/inventory'
      fullPath: '/studio/inventory'
      preLoaderRoute: typeof StudioInventoryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/menu': {
      id: '/studio/menu'
      path: '/menu'
      fullPath: '/studio/menu'
      preLoaderRoute: typeof StudioMenuRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/payments': {
      id: '/studio/payments'
      path: '/payments'
      fullPath: '/studio/payments'
      preLoaderRoute: typeof StudioPaymentsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/pos': {
      id: '/studio/pos'
      path: '/pos'
      fullPath: '/studio/pos'
      preLoaderRoute: typeof StudioPosRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/reports': {
      id: '/studio/reports'
      path: '/reports'
      fullPath: '/studio/reports'
      preLoaderRoute: typeof StudioReportsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/reports/': {
      id: '/studio/reports/'
      path: '/'
      fullPath: '/studio/reports/'
      preLoaderRoute: typeof StudioReportsIndexRouteImport
      parentRoute: typeof StudioReportsRoute
    }
    '/studio/reports/hours': {
      id: '/studio/reports/hours'
      path: '/hours'
      fullPath: '/studio/reports/hours'
      preLoaderRoute: typeof StudioReportsHoursRouteImport
      parentRoute: typeof StudioReportsRoute
    }
  }
}

interface PayRouteChildren {
  PayAffirmRoute: typeof PayAffirmRoute
  PaySuccessRoute: typeof PaySuccessRoute
  PayIndexRoute: typeof PayIndexRoute
}

const PayRouteChildren: PayRouteChildren = {
  PayAffirmRoute: PayAffirmRoute,
  PaySuccessRoute: PaySuccessRoute,
  PayIndexRoute: PayIndexRoute,
}

const PayRouteWithChildren = PayRoute._addFileChildren(PayRouteChildren)

interface StudioReportsRouteChildren {
  StudioReportsHoursRoute: typeof StudioReportsHoursRoute
  StudioReportsIndexRoute: typeof StudioReportsIndexRoute
}

const StudioReportsRouteChildren: StudioReportsRouteChildren = {
  StudioReportsHoursRoute: StudioReportsHoursRoute,
  StudioReportsIndexRoute: StudioReportsIndexRoute,
}

const StudioReportsRouteWithChildren = StudioReportsRoute._addFileChildren(
  StudioReportsRouteChildren,
)

interface StudioRouteChildren {
  StudioAccessRoute: typeof StudioAccessRoute
  StudioCalendarRoute: typeof StudioCalendarRoute
  StudioClientsRoute: typeof StudioClientsRoute
  StudioHoursRoute: typeof StudioHoursRoute
  StudioInventoryRoute: typeof StudioInventoryRoute
  StudioMenuRoute: typeof StudioMenuRoute
  StudioPaymentsRoute: typeof StudioPaymentsRoute
  StudioPosRoute: typeof StudioPosRoute
  StudioReportsRoute: typeof StudioReportsRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAccessRoute: StudioAccessRoute,
  StudioCalendarRoute: StudioCalendarRoute,
  StudioClientsRoute: StudioClientsRoute,
  StudioHoursRoute: StudioHoursRoute,
  StudioInventoryRoute: StudioInventoryRoute,
  StudioMenuRoute: StudioMenuRoute,
  StudioPaymentsRoute: StudioPaymentsRoute,
  StudioPosRoute: StudioPosRoute,
  StudioReportsRoute: StudioReportsRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  PayRoute: PayRouteWithChildren,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  StudioRoute: StudioRouteWithChildren,
  TeamRoute: TeamRoute,
  VisitsRoute: VisitsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
